<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-Diego1733/blob/main/Nov10-11/Nov10_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Propagación hacia adelante:

Lo que queremos es querer construir la red neuronal, cuántas capas y neuronas (Basicamente, cuántos pesos).

### Propagación hacia atrás:

Cómo optimizo esos pesos. Cuando se habla de redes neuronales, se trata de pasar por todas las neuronas, optimizando todos los pesos.


····································································································································································································································

g(X) = activación de neurona

LO QUE DEFINE A UNA NEURONA SON SUS PESOS Y SUS BAYES (B)

Hasta ahora sólo hemos visto una sola neurona, con pesos de la dimensión de la neurona. Construiremos un modelo un poco más avanzado. Pensando en un problema "Predicción de la demanda", estamos en una empresa de X productos, un equipo tiene un producto nuevo y queremos predecir si el producto tendrá una alta demanda en el mercado.

* Analizandolo como humanos: Nuestras variables podrían ser: El producto, el precio, el costo de traslado, marketing, material.
La salida sería la "demanda", podríamos interpretarlo como la probabilidad de que sea un producto muy solicitado. Podríamos hacer una regresión lineal, o verlo como un problema de PCA y predecir.
También podríamos combinarlas y crear nuevas variables:
    

1.   Accesibilidad: Producto, Precio
2.   Conocimiento: Marketing, Producto
3.   Percepción de la calidad: Producto, Material



* Analizando como red neuronal: Cada una de las variables originales podría verse como una neurona con entradas y da una salida, y estas se pueden conectar a una nueva neurona que da la salida a la demanda. Esto sería una neurona de 3 capas. En las redes neuronales no nos importan las variables, nos importan las relaciones que va encontrando en términos de las variables originales. Internamente la red neuronal la red está haciendo una especia de reducción de variables, la que no son útiles, su costo es 0, pero no es específicamente un PCA. La propia neurona se encarga de predecir y en base a la correlación descarta las variables que no contribuyen. ¿Cómo sé que me está prediciendo cada neurona? Generalmente no sabemos, lo importante es el resultado final (Tengo entendido).

En una red neuronal, las neuronas no "saben" de antemano qué hacer o qué predecir. Más bien, el proceso de aprendizaje implica ajustar los pesos y sesgos de las conexiones entre neuronas para que la red pueda realizar tareas específicas.

Cuando se inicializa una red neuronal, los pesos y sesgos se establecen generalmente de manera aleatoria. Durante el entrenamiento, la red se expone a un conjunto de datos de entrenamiento que contiene ejemplos emparejados de entrada y salida deseada. La red ajusta sus pesos y sesgos utilizando un proceso llamado retropropagación, que se basa en el cálculo del gradiente de la función de pérdida con respecto a los pesos.



····································································································································································································································
### ¿Cómo funciona una red neuronal?


1.  Entrada (Input Layer): Esta capa recibe los datos de entrada. Cada nodo en esta capa representa una característica o variable del conjunto de datos.

2.  Pesos y Bias: Cada conexión entre neuronas tiene un peso asociado, que determina la fuerza de la conexión. Además, cada neurona tiene un término de sesgo (bias) que se suma a la entrada ponderada antes de aplicar una función de activación.

3.  Función de Activación: Después de calcular la suma ponderada de las entradas, se aplica una función de activación a ese valor. La función de activación introduce no linealidades en la red, permitiendo que la red aprenda patrones más complejos.

4.  Capas Ocultas (Hidden Layers): Después de la capa de entrada, hay una o más capas ocultas donde se realizan cálculos más complejos. Cada capa oculta tiene su propio conjunto de pesos y bias.

5.  Salida (Output Layer): La última capa produce el resultado final. La cantidad de nodos en esta capa depende del tipo de problema: clasificación binaria, clasificación multiclase, regresión, etc.

6.  Función de Pérdida (Loss Function): Se utiliza una función de pérdida para evaluar cuán bien está haciendo la red en comparación con la verdad conocida. La red ajusta sus pesos y bias para minimizar esta pérdida durante el entrenamiento.

7.  Optimización: Se utiliza un algoritmo de optimización (como el descenso de gradiente) para ajustar los pesos y los bias de la red de manera que se minimice la función de pérdida.

8.  Retropropagación (Backpropagation): Este es el proceso mediante el cual se calcula el gradiente de la función de pérdida con respecto a los pesos de la red. Luego, se utiliza este gradiente para actualizar los pesos mediante el algoritmo de optimización.

9.  Entrenamiento: El modelo se entrena mediante la presentación iterativa de ejemplos de entrenamiento. La red ajusta sus pesos y bias durante el proceso de retropropagación para mejorar su rendimiento.


····································································································································································································································
### Tipos de arquitectura en redes neuronales:

1.  Redes Neuronales Feedforward (FNN):

Estas son las redes neuronales más simples, donde la información fluye en una sola dirección, desde la capa de entrada hasta la capa de salida. Son eficaces para tareas de clasificación y regresión simples.
2.  Redes Neuronales Convolucionales (CNN):

Diseñadas especialmente para procesar datos de tipo cuadrícula, como imágenes. Son muy eficientes para tareas de visión por computadora, reconocimiento de objetos y segmentación de imágenes.
3.  Redes Neuronales Recurrentes (RNN):

Adecuadas para datos secuenciales, como series temporales o texto. Son útiles en tareas como el procesamiento del lenguaje natural (PLN), traducción automática y predicción de series temporales.
4.  Redes Neuronales LSTM (Long Short-Term Memory):

Una variante de las RNN diseñada para abordar el problema de la desaparición del gradiente. Se utilizan comúnmente en tareas que involucran secuencias a largo plazo, como la generación de texto y la traducción automática.
5.  Redes Neuronales Generativas Adversariales (GAN):

Utilizadas para la generación de datos nuevos y realistas. Son populares en aplicaciones de generación de imágenes, como la creación de caras de personas que no existen.
6.  Redes Neuronales Transformer:

Introducidas inicialmente para tareas de procesamiento de lenguaje natural, como la traducción automática. Han demostrado ser eficaces en una variedad de aplicaciones, incluida la visión por computadora y el aprendizaje por refuerzo.
7.  Redes Neuronales Siamesas:

Diseñadas para comparar similitudes entre dos entradas. Son útiles en problemas como la verificación de si dos imágenes son similares o en sistemas de recomendación.
8.  Redes Neuronales Residuales (ResNet):

Introducen conexiones de "salto" para ayudar en el entrenamiento de redes muy profundas. Han sido exitosas en la clasificación de imágenes y otras tareas.

····································································································································································································································


$$ a_{j}^{[l]} = g [ w_{j}^{[l]} · a^{[l-1]} + b_{j}^{[l]}] $$


# Primera red neuronal

In [1]:
import glob
import numpy as np
import copy
import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage

%matplotlib inline

from google.colab import drive
drive.mount('/content/drive')

#Los datos corresponden a un subset del dataset cats vs dogs de https://www.kaggle.com/c/dogs-vs-cats
files = glob.glob('/content/drive/MyDrive/ML2023/CATS_DOGS/*')
M = len(files)
print("M: ", M)

#numero de pixeles para nuestras imágenes.
num_px = 64

# Entrenamiento

train_x = []
train_y = []
for file in files[:100]:
    img = Image.open(file)
    img = img.resize((num_px,num_px))
    data = np.asarray(img)
    train_x.append(data)
    img.close()
    if 'dog' in file:
        train_y.append(1)
    if 'cat' in file:
        train_y.append(0)
train_y = np.asarray(train_y)
train_x = np.asarray(train_x)

# Prueba

test_x = []
test_y = []
for file in files[1700:]:
    #print(file)
    img = Image.open(file)
    img = img.resize((num_px,num_px))
    data = np.asarray(img)
    test_x.append(data)
    img.close()
    if 'dog' in file:
        test_y.append(1)
    if 'cat' in file:
        test_y.append(0)
test_y = np.asarray(test_y)
test_x = np.asarray(test_x)

train_x_flatten = train_x.reshape(train_x.shape[0], -1).T
test_x_flatten = test_x.reshape(test_x.shape[0], -1).T

train_set_y = train_y.reshape((1,train_y.shape[0]))
test_set_y = test_y.reshape((1,test_y.shape[0]))

train_set_x = train_x_flatten/255
test_set_x = test_x_flatten/255

Mounted at /content/drive
M:  1787


In [9]:
# Inicializar los parámetros w y b
def initialize_parameters(dim):
    w = np.random.uniform(0, 0.1, size=(dim, 1))
    b = 0
    return w, b


# Función sigmoide
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Función costo
def compute_cost(A, Y):
    m = Y.shape[1]
    cost = -np.sum(Y * np.log(A) + (1 - Y) * np.log(1 - A)) / m
    return cost

# Propagación hacia adelante para obtener la salida del modelo
def forward_propagation(w, b, X):
    Z = np.dot(w.T, X) + b
    A = sigmoid(Z)
    return A

# Propagación hacia atrás para calcular gradientes
def backward_propagation(X, Y, A):
    m = X.shape[1]
    dz = A - Y
    dw = np.dot(X, dz.T) / m
    db = np.sum(dz) / m
    return dw, db

# Actualizar los parámetros usando el gradiente descendente
def update_parameters(w, b, dw, db, learning_rate):
    w -= learning_rate * dw
    b -= learning_rate * db
    return w, b

# Paso de un solo paso de gradiente descendente
def gradient_descent(X, Y, w, b, learning_rate):

    #Parámetros para gradiente descendente
    Z = np.dot(w.T, X) + b
    A = sigmoid(Z)
    cost = compute_cost(A, Y)

    dz = A - Y
    dw = np.dot(X, dz.T) / X.shape[1]
    db = np.sum(dz) / X.shape[1]

    # Actualizamos parámetros
    w, b = update_parameters(w, b, dw, db, learning_rate)
    return w, b, cost

# Modelo de regresión logística con gradiente descendente
def model_with_gradient_descent(X_train, Y_train, X_test, Y_test, num_iterations, learning_rate):
    w, b = initialize_parameters(X_train.shape[0])

    # Itera para cada uno de nuestros conjuntos de entrenamiento y muestra cada 100
    for i in range(num_iterations):
        w, b, cost = gradient_descent(X_train, Y_train, w, b, learning_rate)

        #if i % 100 == 0:
        #    print(f"Iteración {i}, Costo de entrenamiento: {cost}")

    return w, b

In [3]:
# Número de iteraciones
num_iterations = 1500

# Taza de aprendizaje
learning_rate = 0.01

In [55]:
i = 0
w = []
b = []
a = []

for i in range(2):
  # Retornamos w, a, b
  trained_w_gd, trained_b_gd = model_with_gradient_descent(train_set_x, train_set_y, test_set_x, test_set_y, num_iterations, learning_rate)
  predictions_gd = forward_propagation(trained_w_gd, trained_b_gd, test_set_x)
  w.append(trained_w_gd)
  b.append(trained_b_gd)
  a.append(predictions_gd)

<ipython-input-9-23ebcd8f496d>:15: RuntimeWarning: divide by zero encountered in log
  cost = -np.sum(Y * np.log(A) + (1 - Y) * np.log(1 - A)) / m
<ipython-input-9-23ebcd8f496d>:15: RuntimeWarning: invalid value encountered in multiply
  cost = -np.sum(Y * np.log(A) + (1 - Y) * np.log(1 - A)) / m


In [46]:
w = np.asarray(w)
a = np.asarray(a)
b = np.asarray(b)

In [49]:
print(w.shape)
print(a.shape)
print(b.shape)

(2, 12288, 1)
(2, 1, 87)
(2,)


In [56]:
# Neurona final
def Neurona(w, b, X):
    A = []
    for i in range(2):
      Z = np.dot(w[i], X[i]) + b[i]
    A.append(sigmoid(Z))
    return A
afinal = Neurona(w, b, a)
rounded_predictions_gd = np.round(afinal)
print(afinal)
print(rounded_predictions_gd)

[array([[0.46040249, 0.45783245, 0.45594496, ..., 0.46044033, 0.46010038,
        0.4560276 ],
       [0.46041706, 0.4587822 , 0.45758118, ..., 0.46044113, 0.46022491,
        0.45763377],
       [0.46051712, 0.46531131, 0.46883906, ..., 0.46044662, 0.46108011,
        0.46868449],
       ...,
       [0.46034871, 0.45433   , 0.4499148 , ..., 0.46043738, 0.45964083,
        0.450108  ],
       [0.46043664, 0.46005874, 0.45978103, ..., 0.4604422 , 0.46039223,
        0.45979319],
       [0.46033481, 0.4534256 , 0.44835876, ..., 0.46043662, 0.45952208,
        0.44858045]])]
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
