<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-Diego1733/blob/main/Ago11-12/Ago11_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LISTAS:

In [5]:
list1 = [2, "2", "dos", 2.0]
list2 = [3, "3", 3.0]
print(list1 + list2)      #SUMAR LISTAS
print(list1 * 3)          #QUÉ PASA CUANDO SE MULTIPLICAN LISTAS
list1.append("two")       #AÑADE AL FINAL DE LA LISTA
print(list1)
list1.remove("2")
print(list1)
del list1[2]
print(list1)
print("\n")
#RECORRER LISTAS
for i in list1:
  print(i)
print("\n")

#ESTO ES EQUIVALENTE
for i in range (len(list1)):
  print(list[i])
print("\n")

#IMRPIME LOS ELEMENTOS Y LA ENUMERACIÓN
for i, item in enumerate(list1):
  """
  enumerate regresa dos cosas:
  enumerate(iterable, start=0)
  """
  print(i, item)

[2, '2', 'dos', 2.0, 3, '3', 3.0]
[2, '2', 'dos', 2.0, 2, '2', 'dos', 2.0, 2, '2', 'dos', 2.0]
[2, '2', 'dos', 2.0, 'two']
[2, 'dos', 2.0, 'two']
[2, 'dos', 'two']
2
dos
two


list[0]
list[1]
list[2]


0 2
1 dos
2 two


ARREGLOS

(Qué es una tupla?
 son inmutables, lo que significa que una vez creada una tupla, sus elementos no pueden cambiar)

In [14]:
"""
Para definir un arreglo se deben usar librerías en python, por ejemplo en numpy, array
"""
#ARREGLOS POR
import array as arr

arreglo = arr.array("i", [1, 2, 3])     #arreglo de enteros
print(arreglo)
arreglof = arr.array("f", [1, 2, 3])    #arreglo de flotantes
print(arreglof)
arreglo2 = arr.array("i", [2, 3, 4])

#ARREGLO POR NUMPY
import numpy as np
print("\n")
nparr1 = np.array([1, 2, 3])
print(nparr1)
nparr2 = np.array([4, 5, 6])
print(nparr1 * nparr2)
print(2 * nparr1)
#IMPORTANTE, PARA OPERAR CON ARREGLOS, DEBEN SER DE LA MISMA LONGITUD

print(f"Producto punto: {np.dot(nparr1, nparr2)}")
print(f"División, entonces trabaja elemento a elemento: {nparr1 / nparr2}")


array('i', [1, 2, 3])
array('f', [1.0, 2.0, 3.0])


[1 2 3]
[ 4 10 18]
[2 4 6]
Producto punto: 32


array([0.25, 0.4 , 0.5 ])